language: cpp
compiler:
- gcc
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
sudo: required
before_install:
- sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
install:
- sudo apt-get install cmake
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-6; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
script:
- mkdir bin
- cd bin
- cmake -G "Unix Makefiles" ..
- cmake --build .
- cd tests
- "./tests -r console -s"
before_deploy:
- pwd && ls
deploy:
  skip_cleanup: true
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: "/home/travis/build/blorente/naylang/bin/interpreter/interpreter"
  on:
    repo: blorente/naylang
    branch: master
env:
  global:
    secure: cEgIAN379G8SJa+JFJhzpa6vBbdjDdgz7PXXakgYh+voGJkPZ63JBNSQYKFqrGGrlV0YiLRAhjopHxrqsmmg/W6Y47QWzMipB2koMABabmFFUlmXT9WmDqTVguUEZVxw5y2MNGEtGrJ9nUOXB6Mo4PiGSbOiEX8CB4FQ+CLM602+j0Skj9C5ToPKxRufK6j9ZqG1QNjauexK3LavcVvnAD8Twl1svkb+nqypwNQKLsfoURgZicQmXDUig0zp32j4WfTnw13ndHTElPZTxYi2+diT61GEIJMEg0a9TjIPn0tLG0KEEqUkpipWUXiLU1i/hTBAHZ3PTv+iTFFJtBMlJdk3BFkmml+h6krvugguiEtQh5gMkwN/uGyaOxuZCSFpsKm/leDuCCcFl8WRLn1h3bZFXwRr7JIfVrAHKOrMuXbyg4zZXDN/GRRYExkx9vgmQRg3Gf0TF9GY1S2aFtcgt/8z9GD0r9/J8vkW5hfAa+0Fv6FDtiPRegNE1cKR4Jaa1WkXJUqeNgUVQogfKi5WhiH1gg9jAKrxts34dB5kM5n3NGgfgbgmQzA75JnCmJOyEwqPHnttApl1TRCEsJat6ajFF2xoD/cBlLZu9jNmIKAALoTgr+N6c7y9+v19DrZslAp2NY3G8TcBmKZzJZwuPXnDKsORXn9AmM/m2qbjXzQ=
